### ISSUE TITLE
Ambiente do Usuário

### ISSUE THREAD

**Issue by victorjoaoss** [PetJournal/petjournal.product#6]
[Docs US Ambiente do Usuário](https://docs.google.com/document/d/1Pip6WSiRIkceRmRPyS3UelO1Ws1xPHXB/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)

**Comment by victorjoaoss** [comment]
USER STORY AMBIENTE DO USUÁRIO

Definição:

Como usuário, quero ter acesso a uma tela inicial do aplicativo para que possa navegar pelas funcionalidades disponíveis.


Descrição:

Nessa tela o objetivo é que o usuário tenha acesso a algumas funcionalidades iniciais disponíveis na tela e que possa acessar outras funcionalidades através dos botões e menu disponíveis. 


Protótipo:



![Image](https://user-images.githubusercontent.com/124588899/228326587-cfbea053-2f71-4316-8931-f1a5b59803af.png)













Critérios de Aceite:



- Quando o usuário estiver na tela “Ambiente de uário”, no canto superior esquerdo deverá aparecer a mensagem “Olá <Nome do Tutor> com o primeiro nome da pessoa cadastrada.

- Ao clicar no campo “[Menu](https://docs.google.com/document/d/1yiQRA8q0DPeNrD3AaN0dgqZcSssnij9R/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)”(três barras, canto superior direito) uma tela lateral deverá abrir mostrando opções de configurações do aplicativo.

- Ao clicar no campo “[Blog Pet Journal](https://docs.google.com/document/d/1tLp0QEPyq7VBhkq-zlhjOZV4oO4jAs1q/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)" o usuário deverá ser redirecionado para tela onde contém as matérias disponíveis para leitura. 

- Ao clicar no campo “Ver mais” o usuário deverá ser redirecionado para tela onde terá acesso ao [menu funcionalidades](https://docs.google.com/document/d/1bHoAbtNycRLYxVGKAWRVn-Da1QeolMFE/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).

- Ao clicar no campo “Agenda” o usuário deverá ser direcionado para [agenda pe](https://docs.google.com/document/d/1JNZp_a0OYIZMNDfEZ3rNVAewGkKxuifR/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)t do aplicativo.

- Ao clicar no campo “[Localizar Serviços](https://docs.google.com/document/d/1Y6Sz_vDHMtikHH1jXfFzRfEKB3etrb4p/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)” o usuário deverá ser direcionado para tela onde poderá localizar serviços para o pet na região.

- Ao clicar no campo “[Registrar Vacina](https://docs.google.com/document/d/10CsZ3IC32eabSJM_JPHCIGaoW0R4ggEl/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)” o usuário deverá ser direcionado para tela onde poderá registrar as vacinas que o pet tomou.

- Ao clicar no campo “[Registrar Vermífugo](https://docs.google.com/document/d/10CsZ3IC32eabSJM_JPHCIGaoW0R4ggEl/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)" o usuário deverá ser direcionado para tela onde poderá registrar o vermífugo que o pet já tomou.

- Ao clicar no botão “Home” o usuário deverá voltar para tela de “Ambiente do Usuário”.

- Ao clicar no botão “Pet” o usuário deverá ser direcionado para tela onde ele poderá visualizar, adicionar, editar e excluir informações na tela de [Cadastro de Pet](https://docs.google.com/document/d/10wyu0DwhudWZIDxRz0CSoISLFjnIkI0i/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).

- Ao clicar no botão “[Tutor](https://docs.google.com/document/d/1hb3f3M0VkXC7uMaGhi3P_HvfONhiOOFu/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)” o usuário deverá ser direcionado para tela onde ele poderá visualizar, adicionar, editar e excluir informações pessoais.


Associações:


[Cadastro de Pe](https://docs.google.com/document/d/10wyu0DwhudWZIDxRz0CSoISLFjnIkI0i/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)t.
[Agenda Pet](https://docs.google.com/document/d/1JNZp_a0OYIZMNDfEZ3rNVAewGkKxuifR/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).
[Blog](https://docs.google.com/document/d/1JNZp_a0OYIZMNDfEZ3rNVAewGkKxuifR/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)
[Informações de Perfil](https://docs.google.com/document/d/1hb3f3M0VkXC7uMaGhi3P_HvfONhiOOFu/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).
[Localizar Serviços](https://docs.google.com/document/d/1Y6Sz_vDHMtikHH1jXfFzRfEKB3etrb4p/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).
[Menu de configurações](https://docs.google.com/document/d/1yiQRA8q0DPeNrD3AaN0dgqZcSssnij9R/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).
[Menu de Funcionalidade](https://docs.google.com/document/d/1bHoAbtNycRLYxVGKAWRVn-Da1QeolMFE/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).
[Registro de Vacinas](https://docs.google.com/document/d/10CsZ3IC32eabSJM_JPHCIGaoW0R4ggEl/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).
[Registro de Vermífugo](https://docs.google.com/document/d/10CsZ3IC32eabSJM_JPHCIGaoW0R4ggEl/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true).

**Comment by victorjoaoss** [comment]
@jecilene

**Comment by ClevinhoUX** [comment]
![Image](https://user-images.githubusercontent.com/121971438/228988071-b42ade87-5ccb-4ee5-bf63-463706352b0b.png)

Tenho algumas observações referente a essa tela:
- Na Tab_bar: porque Tutor e não Perfil? Da pra manter perfil?

- Nessa tela foi adicionado o "Olá, primeiro nome do usuário (tutor)"
- Mudei os icons do "Agenda" e "Localizar Serviços"

**Comment by victorjoaoss** [comment]
@ClevinhoUX Tudo bem?

Eu até tinha mandado lá no Discord e a decisão de mudar o Tab_bar de "Perfil" para "Tutor", foi a  de acordo com o que Ju falou, o termo "Tutor" traz essa pegada de carinho, cuidado e zelo e é justamente isso que queremos para o nosso produto.

**Comment by victorjoaoss** [comment]
@ClevinhoUX eu não entendi por que a imagem está com essas faixas laranja.

**Comment by victorjoaoss** [comment]
@ClevinhoUX @julianarib vocês poderiam colocar a imagem atualizada da tela de ambiente de cadastro aqui na US.

**Comment by julianarib** [comment]
![Image](https://user-images.githubusercontent.com/129545369/229885156-85fa92c6-eb1d-4986-8782-3b8ad90440c6.jpg)

**Comment by senegalha** [comment]
@PetJournal/product-team 

Seria o nome completo ou apenas o primeiro nome do tutor?

**Comment by senegalha** [comment]
@PetJournal/android-team @PetJournal/backend-team @PetJournal/frontend-team @PetJournal/ios-team @PetJournal/product-team @PetJournal/qa-team 

**Sugestão**:

Não seria melhor criarmos as telas mencionadas na User Storie e quando finalizadas compilarmos todas elas nessa User Storie de Ambiente de Usuário?

**Comment by Marii-brito** [comment]
@dansenpir , somente o primeiro nome do tutor

**Comment by gusoliveira21** [comment]
Pergunta, o que seria blog e quem iria criar conteúdo pra ele?
E sobre localizar serviços, seria algo relacionado ao aplicativo maps ? 
Tinha a mesma dúvida com relação a agenda, mas foi sanada na call de hoje.
@Marii-brito

**Comment by gusoliveira21** [comment]
### Empedimentos:
- Estudar DataStore
- Estudar Room
- Estudar API do Google Agenda (free tem limite de requisições)
- Estudar Api de maps (free tem limite de requisições)

### LAYOUT

### VIEWMODEL
	Se login is success()
		if cache.name Null -> cache.name = getNameUseCase(cache.token,  email)
	Se não
		falha

### DOMAIN
	return getName(email)

### DATA
	return getNameApi(cache.token, email)

### TESTE
	criar o teste unitário para testar a funcionalidade

**Comment by Marbarret** [comment]
Dúvida: O menu lateral vai ser mostrado como? Precisaríamos de uma base visual para construir ele de acordo com o time de UI.

**Comment by Marii-brito** [comment]
@PetJournal/pet-journal-team 

Fizemos um pequeno ajuste na tela do Ambiente do Usuário. 

No nosso fluxo de cadastrado de usuário não há solicitação de imagem para o usuário de PetJournal, e nessa tela, há a imagem do usuário. 

**_Por agora, resolvemos não manter a imagem do usuário na tela de "Ambiente do Usuário"._** 

Segue a alteração realizada pelo o @PetJournal/ux-team 


![Image](https://user-images.githubusercontent.com/129445779/236315369-dbe19fc0-2d09-44f4-af4b-4f7f539aede5.png)

**Comment by daigoncalves14** [comment]
menu lateral direito, ja vai ter funcionalidade de puxar o menu? vai implementar agora?

**Comment by Marii-brito** [comment]
Oi @daigoncalves14 irá ter sim, mas vamos amuderecer a ideia ainda. Iremos implementar mais tarde

**Comment by Marii-brito** [comment]
Essa Issue foi fechada, e será continuada nesse tópico: #22
